general {
    lock_cmd = pidof hyprlock || hyprlock       # avoids launching multiple instances
    before_sleep_cmd = loginctl lock-session    # locks before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turns on display after sleep
}

# Lock screen after 5 minutes
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn off monitor after 10 minutes
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend PC after 30 minutes
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
